# ======================================
# Production Docker Compose Configuration
# ======================================
# 生产环境Docker Compose配置
# 使用方法：docker-compose -f docker-compose.prod.yml up -d

services:
  # ======================================
  # WeBlog 后端应用 - 生产环境
  # ======================================
  weblog-app:
    image: ${DOCKER_IMAGE:-weblog-backend}:${DOCKER_TAG:-latest}
    container_name: weblog-prod
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      # ======================================
      # Environment Profile
      # ======================================
      - ENV=production

      # ======================================
      # Database Configuration
      # ======================================
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-weblog}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

      # ======================================
      # Application Configuration
      # ======================================
      - SERVER_PORT=8080
      - INIT_MODE=never
      - DDL_AUTO=validate

      # ======================================
      # Development Settings (Disabled)
      # ======================================
      - DEVTOOLS_ENABLED=false
      - LIVERELOAD_ENABLED=false
      - SHOW_SQL=false
      - FORMAT_SQL=false

      # ======================================
      # Logging Configuration
      # ======================================
      - LOG_LEVEL=WARN
      - APP_LOG_LEVEL=INFO
      - WEB_LOG_LEVEL=WARN
      - SQL_LOG_LEVEL=WARN

      # ======================================
      # Security Configuration
      # ======================================
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      - CORS_ORIGINS=${CORS_ORIGINS:-https://yourdomain.com}

      # ======================================
      # AWS Configuration
      # ======================================
      - S3_BUCKET=${S3_BUCKET:-}
      - CLOUDFRONT_DOMAIN=${CLOUDFRONT_DOMAIN:-}
      - AWS_REGION=${AWS_REGION:-us-east-1}

      # ======================================
      # JVM Configuration
      # ======================================
      - JAVA_OPTS=-Xmx512m -Xms256m -XX:+UseG1GC -XX:+UseContainerSupport

    restart: unless-stopped

    # ======================================
    # Health Check
    # ======================================
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    # ======================================
    # Resource Limits
    # ======================================
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"

# ======================================
# Networks
# ======================================
networks:
  default:
    name: weblog-prod-network
